### ISSUE TITLE
test 时evaluation输出的mAP都是-1

### ISSUE THREAD

**Issue by Happyna88** [pengzhiliang/Uodac_sonar#1]
同学,你好, 我刚跑了一下test_sonar.sh, 发现最后输出的mAP都是-1, 是只输出prediction文件,并没有计算mAP吗?另外你对要检测的目标物是怎么理解的?大致看着像是相对亮的部分. 但有些看着也像是目标物,但是train_annotation 并没有给ground_truth, 你对数据集有做清理或者其他前处理工作吗?我还没有完全弄懂code, 可能问了一些低级的问题,望指教.谢谢.

**Comment by pengzhiliang** [comment]
你好，首先，直接跑test_sonar.sh会得到bbox的map，你得到的-1可能是数据问题，也可能是你选的模型问题，你可以直接下载我之前训好的模型。其次，这个比赛数据集定义的物体确实很迷，我也不是很懂，然后标注框也是非常不准，我也没办法，抱歉。最后，我只是对进行了一下数据增强，倒是没有清理数据，因为根本就没几张有用的数据。

**Comment by Happyna88** [comment]
> 你好，首先，直接跑test_sonar.sh会得到bbox的map，你得到的-1可能是数据问题，也可能是你选的模型问题，你可以直接下载我之前训好的模型。其次，这个比赛数据集定义的物体确实很迷，我也不是很懂，然后标注框也是非常不准，我也没办法，抱歉。最后，我只是对进行了一下数据增强，倒是没有清理数据，因为根本就没几张有用的数据。

谢谢你的回答. 我先是用你训练好的网络做的test_sonar.sh,  我今天看了下代码,  cocoGt.dataset['annotations']是空的,所以没有mAP结果.而cocoGt是从data/annotation/a-test.json文件读取的, 该文件里没有annotations数据, 这个a-test.json文件我是从你的百度网盘上下载的, 这个文件我想应该重新生成一下, 要不没有ground_truth 数据. 
sonar图像相对于光学图像,噪声大,样本少, 我想是不是可以做一些前期去噪等操作, 逐步研究下.
谢谢

**Comment by pengzhiliang** [comment]
test确实是没有ground truth的，只在测试的服务器上有，类似于coco数据集的设置。你可以自己生成一些val set测试一下。前期的简单的高斯平滑之类的好像确实没啥用，不过你可以再研究一下。

**Comment by Happyna88** [comment]
好的,明白, 我再重新生成试一下.  另外,我刚试了一下train_sonar.sh, 打印了很多, 有下面的提示, pretrain_model我是从你给的模型准备的第一个预训练模型的百度网盘下来的, 是这个吗? 多谢啦.

2020-12-23 16:56:50,325 - mmdet - INFO - load model from: pretrain_model/cascade_rcnn_dconv_c3-c5_r101_dufpn_1x.pth
2020-12-23 16:56:50,574 - mmdet - WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: backbone.conv1.weight, backbone.bn1.weight, backbone.bn1.bias, backbone.bn1.running_mean,..........................................
size mismatch for rpn_head.rpn_cls.weight: copying a param with shape torch.Size([3, 256, 1, 1]) from checkpoint..........................
